services:
  hapi-server:
    build: .
    image: hapi-pg-docker:1.0.0
    container_name: hapi-server
    ports:
      - "3001:3001"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    depends_on:
      - hapi-pg-docker-postgres
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST: "${POSTGRES_HOST:-hapi-pg-docker-postgres}"
      POSTGRES_USERNAME: "${POSTGRES_SCHEMA_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_SCHEMA_PASSWORD}"
      POSTGRES_PORT: "5432"
      POSTGRES_SCHEMA_NAME: "${POSTGRES_SCHEMA_NAME:-public}"

  hapi-pg-docker-postgres:
    image: postgres
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USERNAME: "${POSTGRES_SCHEMA_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_SCHEMA_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: